name: personal_portfolio
description: A new Flutter project for personal portfolio.

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Add your dependencies here.
  # Example:
  cupertino_icons: ^1.0.2
  flutter_gen: ^5.6.0   # FlutterGen for generating assets
  dotted_border: ^2.1.0
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Include FlutterGen as a dev dependency
  build_runner: ^2.1.10
  flutter_gen_runner: ^5.0.3

flutter:
  uses-material-design: true

  # Declare your assets here.
  assets:
    - assets/pngs/
    - assets/svgs/

  # Declare your fonts here.
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
        - asset: assets/fonts/Inter_18pt-Italic.ttf
        - asset: assets/fonts/Inter_18pt-BoldItalic.ttf
        - asset: assets/fonts/Inter_18pt-Black.ttf
        - asset: assets/fonts/Inter_18pt-BlackItalic.ttf
        - asset: assets/fonts/Inter_18pt-ExtraBold.ttf
        - asset: assets/fonts/Inter_18pt-ExtraBoldItalic.ttf
        - asset: assets/fonts/Inter_18pt-ExtraLight.ttf
        - asset: assets/fonts/Inter_18pt-ExtraLightItalic.ttf
        - asset: assets/fonts/Inter_18pt-Light.ttf
        - asset: assets/fonts/Inter_18pt-LightItalic.ttf
        - asset: assets/fonts/Inter_18pt-Medium.ttf
        - asset: assets/fonts/Inter_18pt-MediumItalic.ttf
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
        - asset: assets/fonts/Inter_18pt-SemiBoldItalic.ttf
        - asset: assets/fonts/Inter_18pt-Thin.ttf
        - asset: assets/fonts/Inter_18pt-ThinItalic.ttf
        - asset: assets/fonts/Inter_24pt-Regular.ttf
        - asset: assets/fonts/Inter_24pt-Bold.ttf
        - asset: assets/fonts/Inter_24pt-Italic.ttf
        - asset: assets/fonts/Inter_24pt-BoldItalic.ttf
        - asset: assets/fonts/Inter_24pt-Black.ttf
        - asset: assets/fonts/Inter_24pt-BlackItalic.ttf
        - asset: assets/fonts/Inter_24pt-ExtraBold.ttf
        - asset: assets/fonts/Inter_24pt-ExtraBoldItalic.ttf
        - asset: assets/fonts/Inter_24pt-ExtraLight.ttf
        - asset: assets/fonts/Inter_24pt-ExtraLightItalic.ttf
        - asset: assets/fonts/Inter_24pt-Light.ttf
        - asset: assets/fonts/Inter_24pt-LightItalic.ttf
        - asset: assets/fonts/Inter_24pt-Medium.ttf
        - asset: assets/fonts/Inter_24pt-MediumItalic.ttf
        - asset: assets/fonts/Inter_24pt-SemiBold.ttf
        - asset: assets/fonts/Inter_24pt-SemiBoldItalic.ttf
        - asset: assets/fonts/Inter_24pt-Thin.ttf
        - asset: assets/fonts/Inter_24pt-ThinItalic.ttf
        - asset: assets/fonts/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter_28pt-Bold.ttf
        - asset: assets/fonts/Inter_28pt-Italic.ttf
        - asset: assets/fonts/Inter_28pt-BoldItalic.ttf
        - asset: assets/fonts/Inter_28pt-Black.ttf
        - asset: assets/fonts/Inter_28pt-BlackItalic.ttf
        - asset: assets/fonts/Inter_28pt-ExtraBold.ttf
        - asset: assets/fonts/Inter_28pt-ExtraBoldItalic.ttf
        - asset: assets/fonts/Inter_28pt-ExtraLight.ttf
        - asset: assets/fonts/Inter_28pt-ExtraLightItalic.ttf
        - asset: assets/fonts/Inter_28pt-Light.ttf
        - asset: assets/fonts/Inter_28pt-LightItalic.ttf
        - asset: assets/fonts/Inter_28pt-Medium.ttf
        - asset: assets/fonts/Inter_28pt-MediumItalic.ttf
        - asset: assets/fonts/Inter_28pt-SemiBold.ttf
        - asset: assets/fonts/Inter_28pt-SemiBoldItalic.ttf
        - asset: assets/fonts/Inter_28pt-Thin.ttf
        - asset: assets/fonts/Inter_28pt-ThinItalic.ttf
