name: personal_portfolio
description: A new Flutter project for personal portfolio.

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Add your dependencies here.
  # Example:
  cupertino_icons: ^1.0.2
  flutter_gen: ^5.6.0   # FlutterGen for generating assets
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Include FlutterGen as a dev dependency
  build_runner: ^2.1.10
  flutter_gen_runner: ^5.0.3

flutter:
  uses-material-design: true

  # Declare your assets here.
  assets:
    - assets/pngs/bg.png

  # Declare your fonts here.
  fonts:
    - family: ComicNeue
      fonts:
        - asset: assets/fonts/ComicNeue-BoldItalic.ttf
        - asset: assets/fonts/ComicNeue-Bold.ttf
        - asset: assets/fonts/ComicNeue-Italic.ttf
        - asset: assets/fonts/ComicNeue-LightItalic.ttf
        - asset: assets/fonts/ComicNeue-Light.ttf
        - asset: assets/fonts/ComicNeue-Regular.ttf

    - family: Kalam
      fonts:
        - asset: assets/fonts/Kalam-Bold.ttf
        - asset: assets/fonts/Kalam-Light.ttf
        - asset: assets/fonts/Kalam-Regular.ttf

    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-BoldItalic.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu-Italic.ttf
        - asset: assets/fonts/Ubuntu-LightItalic.ttf
        - asset: assets/fonts/Ubuntu-Light.ttf
        - asset: assets/fonts/Ubuntu-MediumItalic.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu-Regular.ttf
