name: personal_portfolio
description: A new Flutter project for personal portfolio.

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Add your dependencies here.
  # Example:
  cupertino_icons: ^1.0.2
  flutter_gen: ^5.6.0   # FlutterGen for generating assets
  dotted_border: ^2.1.0
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Include FlutterGen as a dev dependency
  build_runner: ^2.1.10
  flutter_gen_runner: ^5.0.3

flutter:
  uses-material-design: true

  # Declare your assets here.
  assets:
    - assets/pngs/
    - assets/svgs/

  # Declare your fonts here.
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
        - asset: assets/fonts/Inter_18pt-Italic.ttf
        - asset: assets/fonts/Inter_24pt-Regular.ttf
        - asset: assets/fonts/Inter_24pt-Bold.ttf
        - asset: assets/fonts/Inter_28pt-Regular.ttf
